<script>

	import '../../../assets/global-styles.css';

	import Logo from '$lib/LogoBody.svelte';
	import TitleVideo from '$lib/TitleVideo.svelte';
    import TitlePage from '$lib/TitlePage.svelte';
	import AuthorDate from '$lib/AuthorDate.svelte';
	import ImageSingle from '$lib/ImageSingle.svelte';
	import GraphicSingle from '$lib/GraphicSingle.svelte';
	import GraphicsMultiples from '$lib/GraphicMultiples.svelte';
	import Footer from '$lib/Footer.svelte';
	import ScrollyImages from "$lib/ScrollyImages.svelte";
	import LineBreakMiniTransitMap from '$lib/LineBreakMiniTransitMap.svelte';
	import Password from '$lib/Password.svelte';
	import Recommendation from '$lib/Recommendation.svelte';
	import LogoBody from '$lib/LogoBody.svelte';
	
	import BoilerPlate from '$lib/BoilerPlate.svelte';
	import Footnote from '$lib/Footnote.svelte';
	import Footnotes from '$lib/Footnotes.svelte';
	import { createFootnoteStore } from '$lib/footnoteUtils';

	const footnoteStore = createFootnoteStore();
	const { footnotes, addFootnote } = footnoteStore;

	const fns = [
		'Rafael H. M. Pereira and Alex Karner, “Transportation Equity,” in International Encyclopedia of Transportation, vol. 1, ed. Roger Vickerman (2021), <a href="http://dx.doi.org/10.1016/B978-0-08-102671-7.10053-3" target="_blank">DOI</a>.',
		'Alex Karner, Rafael H. M. Pereira, and Steven Farber, “Advances and Pitfalls in Measuring Transportation Equity,” in Transportation, ahead of print, January 12, 2024. <a href="https://doi.org/10.1007/s11116-023-10460-7" target="_blank">DOI</a>.',
		'Institute of Transportation Engineers (ITE), Trip Generation , 8th Edition (ITE, 2008). e',
		'Reid Ewing et al., “Traffic Generated by Mixed-Use Developments—Six-Region Study Using Consistent Built Environmental Measures,” in Journal of Urban Planning and Development 137, no. 3 (2011): 248–61, <a href="https://doi.org/10.1061/(ASCE)UP.1943-5444.0000068" target="_blank">DOI</a>. '
	];

	const credits = [
		{ role:"Research", names:"Brenn Anderson-Gregson, Steve Farber"},
		{ role:"Additional writing", names:"Anika Reisha Taboy, Kathryn Exon Smith"},
		{ role:"Data visualization", names:"Jeff Allen"},
		{ role:"Web development", names:"Mieko Yao, Jeff Allen"}
	]

</script>



<svelte:head>

	<title>TOD Research - Transportation Equity | School of Cities</title>

	<!-- <meta name="description" content="Repository of design and web components for building data stories, visualizations, maps, and other custom web projects" />
	<meta name="author" content="School of Cities">
	<meta rel="canonical" href="https://schoolofcities.github.io/design-components/">

	<meta property="og:title" content="Design Components" />
	<meta property="og:description" content="Repository of design and web components for building data stories, visualizations, maps, and other custom web projects" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://schoolofcities.github.io/design-components/" />
	<meta property="og:image" content="https://raw.githubusercontent.com/schoolofcities/design-components/main/static/web-card.png" />
	<meta property="og:locale" content="en_CA">

	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content="Design Components" />
	<meta name="twitter:description" content="Repository of design and web components for building data stories, visualizations, maps, and other custom web projects" />
	<meta name="twitter:site" content="https://schoolofcities.github.io/design-components/" />
	<meta name="twitter:image" content="https://raw.githubusercontent.com/schoolofcities/design-components/main/static/web-card.png" /> 

	<meta name="citation_title" content="Design Components">
	<meta name="citation_author" content="Author Name 1">
	<meta name="citation_author" content="Author Name 2">
	<meta name="citation_author" content="Author Name 3"> -->
	<meta name="citation_publication_date" content="2025/09/23">
	<meta name="citation_journal_title" content="School of Cities">
	<!-- <meta name="citation_pdf_url" content="https://schoolofcities.utoronto.ca/research-paper.pdf"> -->
	<!-- <meta name="citation_abstract_html_url" content="https://schoolofcities.github.io/design-components/"> -->

</svelte:head>



<main>

	<Password correctPassword="meowmeowcat"></Password>

	<!-- <TitleVideo
		title="Transportation equity and sustainable mobility from mixed-use development"
		subtitle=""
		titletype="RESEARCH"
		video="/tod-on-main/research/embodied-carbon/skylineVideo.mp4"
		videoSpeed={0.67}
		videoOpacity={0.8}
		titleFontColour="var(--brandWhite)"
		subtitleFontColour="var(--brandWhite)"
		logoType = 'White';
	/> -->
	<TitlePage
		title="Transportation equity and sustainable mobility from mixed-use development"
		type="Research"
		bgType="Video"
		url="/tod-canada/web-assets/research/transportation-equity/people-walking-on-sidewalk_1080.mp4"
		videoSpeed={0.67}
		videoOpacity={0.98}
		titleFontColour="var(--brandWhite)"
		subtitleFontColour="var(--brandWhite)"
		logoType = 'White';
		backgroundColour = "black"
	/>

	<div class="text" style="margin-top: 80px">

		<AuthorDate
			credits={credits} date="March 2026"
		/>

	</div>

	

	<div class="text">
		<h1>
			The big picture
		</h1>
		<p>
			New developments, including changes to land use, population, and employment patterns, influence how people travel and alter the distribution of transportation-related advantages and disadvantages. This study measures how transit-oriented development (TOD) affects two important metrics: transportation equity and sustainable mode shift.  
		</p>
		<p>	
			<span class="highlight" style="background-color: #F1C500; color: black;opacity: 0.8;">Transportation equity</span> asks who gains access to mobility and opportunity, who faces costs or constraints, and what the magnitudes of those impacts are.<Footnote id={addFootnote(fns[0])}/>
		</p>
		<p>	
			<span class="highlight" style="background-color: #F1C500; color: black;opacity: 0.8;">Mode shift</span> evaluates how development patterns influence sustainable transportation outcomes by looking at the percentage of people who switch from driving to more sustainable modes of travel, such as transit, walking, or cycling. 
		</p>
		<p>	
			By projecting how a development may reshape where people live and work, we can assess how different scenarios will reduce or exacerbate transportation disadvantage and sustainability. 
		</p>

		<BoilerPlate pageType="Research"/>

		
		<h1>
			Methodology and approach 
		</h1>
		<p>
			Our focus in measuring transportation equity was on understanding how people living in poverty, as defined by <a href="https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1110024101" target="_blank">Statistics Canada’s Low Income Cut-Off</a> threshold, could access employment opportunities under different development scenarios. To assess the potential impact of different types of TOD, we implemented <a href="https://en.wikipedia.org/wiki/Foster–Greer–Thorbecke_indices" target="_blank">Foster-Greer-Thorbecke Indices</a>, which quantify how over-represented low-income households are in areas of transport disadvantage.<Footnote id={addFootnote(fns[1])}/> 
		</p>
		<p>	
			We began by assessing <span class="highlight" style="background-color: #AB1368; color: white;opacity: 0.8;">current conditions</span>, using census data for low-income households and business register data for employment, to calculate baseline accessibility scores at the dissemination area level. We then created three development scenarios: 
		</p>

		<ul>
			<li>
				A <span class="highlight" style="background-color: #007894; color: white;opacity: 0.8;">current trajectory</span>, which follows existing growth patterns within the TOD 
			</li>
			<li>
				A <span class="highlight" style="background-color: #00A189; color: white;opacity: 0.8;">optimized scenario</span>, which uses more optimal land use changes within the TOD 
			</li>
			<li>	
				A <span class="highlight" style="background-color: #6D247A; color: white;opacity: 0.8;">general growth scenario</span> which assumes the same population and job growth as in the current trajectory but distributes it across the municipalities3 rather than concentrating it in the station area, in proportion to their existing values 
			</li>
		</ul>

		<p>
			To evaluate sustainable mode shift, we used trip generation analysis to estimate the number and types of trips associated with the current trajectory and optimized development scenarios above, compared to existing conditions. Here we apply the <a href="https://envisiontomorrow.org/site-mxd/" target="_blank">Mixed-Use District Travel Model</a> from Envision Tomorrow because the industry standard model for measuring trip generation uses estimates that are largely based on suburban locations with limited pedestrian or transit infrastructure, making it less suitable for mixed-use and transit-oriented developments.<Footnote id={addFootnote(fns[2])}/> From this model, we selected the variables most affected by TOD, namely population, employment, land use, and residential dwelling mix<Footnote id={addFootnote(fns[3])}/> as well as outcome variables for each scenario:   
		</p>

		<ul>
			<li>
				<strong>Sustainable mode share:</strong> the percentage of trips made by sustainable modes 
			</li>
			<li>
				<strong>Sustainable mode shift:</strong> the increase in sustainable mode share from the baseline scenario to the new scenario (e.g. a 10% rise in walking trips) 
			</li>
			
		</ul>

		<p>
			Click here for a more detailed discussion of the methodology. 
		</p>

	</div>

	<!-- <GraphicSingle
		svg720={"../web-assets/research/transportation-equity/edmonton-access-example-720.svg"}
		svg360={"../web-assets/research/transportation-equity/poverty-scenario-360.svg"}
	/> -->

	<div class="text">

		<h1>
			What we found 
		</h1>

		<p>
			Our findings show that development around transit stations is beneficial both for equity and sustainability outcomes. 
		</p>

		<h2>
			TOD increases transportation access and equity
		</h2>

		<p>
			Compared with a general growth scenario, densifying near transit – whether along the current trajectory or in an optimized scenario – increases equity by allowing more low-income households to access opportunities within their neighbourhoods and through the transit network. This finding was consistent across all of the sites studied. The depth of the impact is closely tied to the number of affordable units included in the development, so increasing the number of affordable units will amplify transportation equity benefits, extending this access to thousands more families. 
		</p>

	</div>

	<GraphicSingle
		svg720={"../web-assets/research/transportation-equity/poverty-scenario-720.svg"}
		svg360={"../web-assets/research/transportation-equity/poverty-scenario-360.svg"}
	/>

	<div class="text">

		<h2>
			TOD consistently enables a shift to more sustainable modes 
		</h2>

		<p>
			Across all case studies, new development in both scenarios of mixed-use TOD districts reduces vehicle trips and increases transit and walking trips for both internal and external travel compared with general growth. These shifts reflect the combined effects of increasing the diversity of land uses, shorter trip distances, and improved access to non-auto modes within station areas. While the direction of change is consistent, the magnitude of the sustainable mode shift and final mode share varies across the case studies, reflecting differences in local context, scale, and network connectivity.   
		</p>

	</div>

	<GraphicSingle
		svg720={"../web-assets/research/transportation-equity/mode-shift-720.svg"}
		svg360={"../web-assets/research/transportation-equity/mode-shift-360.svg"}
	/>

	<div class="text">

		<h2>
			Transit improvements should be directed to larger station areas with limited existing access
		</h2>

		<p>
			Larger station areas – those with more people and jobs – show higher absolute sustainable mode shares following new development, which reflects broader urban patterns showing that people tend to walk and take transit more in larger, denser cities. Yet the sustainable mode shift in these areas is proportionally lower, with the largest station areas showing only modest increases. In these areas, significant shifts in sustainable mode share cannot be achieved by development in a single mixed-use district: these areas are already well served, so increased development with existing service shows only marginal returns.    
		</p>

	</div>

	<GraphicSingle
		svg720={"../web-assets/research/transportation-equity/population-mode-shift-720.svg"}
		svg360={"../web-assets/research/transportation-equity/population-mode-shift-360.svg"}
	/>

	<div class="text">

		<p>
			However, cities can see greater sustainable mode shifts by increasing transit investment in these areas, which can connect them with a greater number of jobs in the region. Planned investments such as the Hazel McCallion light rail transit line in Cooksville may therefore have a significant impact on converting external vehicle trips into transit trips. Larger station areas that can better connect into existing or planned higher-order transit networks are better positioned to realize meaningful mode share gains. 
		</p>

	</div>

	<GraphicSingle
		svg720={"../web-assets/research/transportation-equity/land-use-mode-shift-720.svg"}
		svg360={"../web-assets/research/transportation-equity/land-use-mode-shift-360.svg"}
	/>

	<div class="text">

		<h2>
			Smaller station areas benefit most from a greater mix of uses 
		</h2>

		<p>
			Transit investments in smaller communities, while important overall for increasing access and densifying the transit networks, might have smaller mode share impacts due to lower regional employment numbers. For these stations, meaningful shifts are more likely to come from a greater mix of uses. More mixed-use development in the smaller TODs we studied leads to substantial increases in trips that occur within the area, supporting more walking and shorter vehicle trips that remain within the station area.   
		</p>

		<p>
			While vehicle travel continues to dominate overall, these internal shifts represent an important restructuring of travel behaviour at the local scale. This is particularly significant for smaller or less developed station areas with vacant or underutilized land like Panama Station, where development can significantly increase internal trips and shorten travel distances. Although total sustainable mode share remains comparatively lower, the magnitude of change from existing conditions is substantial, representing a critical first step toward longer-term reductions in auto dependence. 
		</p>

		<p>
			See the full analysis here. 
		</p>

		<h1>
			Key conclusions and policy recommendations 
		</h1>

		<p>
			Our analysis demonstrates that mixed-use development consistently supports shifts away from vehicle travel, but that the scale of these shifts depends strongly on station context. While land use mix is a necessary condition for encouraging walking and transit use, it is not sufficient on its own to generate large increases in overall sustainable mode share. Instead, site population, employment, and access to jobs accessible by transit and walking emerge as the primary determinants of absolute mode share outcomes.  
		</p>

		<p>
			The findings point to a clear distinction between where large mode share gains are achievable and how progress can be made across different station types. In larger station areas, sustainable mode share is largely shaped by regional connectivity and transit network capacity, meaning that substantial gains depend on transportation investment as much as land use. In smaller areas, where regional accessibility is more constrained, the most impactful changes occur through relative mode shifts driven by land use mixing, shorter travel distances, and internal trips produced and fulfilled through new development.  
		</p>

		<div class="quote">
			<p>
				Mixed-use development provides important benefits across all station areas, but concentrating employment uses near transit can maximize transportation accessibility outcomes. 
			</p>
		</div>


		<Recommendation count=1 title="Target transportation investments within larger station areas"/>

		<p>
			For larger station areas with high population and employment concentrations, transportation investments play a critical role in increasing sustainable mode share. Policies should prioritize investments that expand the number of regional jobs accessible by transit and walking, including higher-order transit projects, service frequency upgrades, and stronger network integration.  
		</p>

		<p>
			By improving regional accessibility, these investments can convert external vehicle trips into transit trips and amplify the effects of existing density and land use mix. For larger station areas, transportation investments are likely to yield the greatest returns in terms of absolute mode share change, particularly where development can leverage existing or planned transit corridors.  
		</p>

		<Recommendation count=2 title="Promote more land use mixing in smaller station areas"/>

		<p>
			In smaller station areas, where population and employment levels are lower and regional accessibility is more limited, large increases in sustainable mode share may be difficult to achieve in the short term. In these instances, policies should focus on increasing land use mix to encourage internal trips and shorten travel distances.  
		</p>

		<p>
			Encouraging higher land use diversity – through flexible zoning, infill development, and the inclusion of complementary residential, employment, and service uses – can produce substantial relative shifts toward walking and transit, even if absolute mode shares remain modest. These shifts can lay the groundwork for future transportation investments as station areas intensify.  
		</p>

		<Recommendation count=3 title="Include more affordable units in TOD areas "/>

		<p>
			Incorporating affordable housing within mixed-use developments can greatly enhance accessibility for disadvantaged residents, allowing them to live near transit, jobs, and local services. This reduces reliance on private vehicles and supports more sustainable travel patterns. Affordable units also ensure that the benefits of TOD – shorter commutes, improved access, and connections to opportunities – are shared across all income groups.  
		</p>

		<div class="line-break"></div>

	</div>

	<Footnotes footnotes={footnotes} />

	<div class="text">
		<div class="line-break"></div>
		<LogoBody/>
		<div class="line-break"></div>
	</div>


</main>
